export const ActionTypes = {
  SET_COMPANIES: "SET_COMPANIES",
  SET_SELECTED_COMPANY: "SET_SELECTED_COMPANY",

  SET_PHONES: "SET_PHONES",
  SET_SELECTED_PHONE: "SET_SELECTED_PHONE",

  SET_IS_OPEN: "SET_IS_OPEN",
  SET_PANEL_TYPE: "SET_PANEL_TYPE",
};
