export const ActionTypes = {
  SET_COMPANIES: "SET_COMPANIES",
  ADD_COMPANY: "ADD_COMPANY",
  EDIT_COMPANY: "EDIT_COMPANY",

  SET_COMPANY_ROW_DATA: "SET_COMPANY_ROW_DATA",

  SET_DRIVERS: "SET_DRIVERS",
  ADD_DRIVERS: "ADD_PHONES",
  
  SET_DRIVER_ROW_DATA: "SET_PHONE_ROW_DATA",

  SET_SELECTED_PHONE: "SET_SELECTED_PHONE",

  SET_IS_OPEN: "SET_IS_OPEN",
  SET_PANEL_TYPE: "SET_PANEL_TYPE",
  SET_PANEL_TITLE: "SET_PANEL_TITLE",

  SET_IS_EXPANDED: "SET_IS_EXPANDED",

  SET_MAP_ORIGIN: "SET_MAP_ORIGIN",
  SET_MAP_DESTINATION: "SET_MAP_DESTINATION",
};
