export const ActionTypes = {
  SET_COMPANIES: "SET_COMPANIES",
  ADD_COMPANY: "ADD_COMPANY",

  SET_SELECTED_COMPANY: "SET_SELECTED_COMPANY",

  SET_PHONES: "SET_PHONES",
  ADD_PHONES: "ADD_PHONES",

  SET_SELECTED_PHONE: "SET_SELECTED_PHONE",

  SET_IS_OPEN: "SET_IS_OPEN",
  SET_PANEL_TYPE: "SET_PANEL_TYPE",
  SET_PANEL_TITLE: "SET_PANEL_TITLE",

  SET_IS_EXPANDED: "SET_IS_EXPANDED",

  SET_MAP_ORIGIN: "SET_MAP_ORIGIN",
  SET_MAP_DESTINATION: "SET_MAP_DESTINATION",
};
